package com.example.LabTech.entite.enums;

public enum Materiel_type {
    SPECTROPHOTOMETRE,
    MICROSCOPE,
    CENTRIFUGEUSE,
    AUTOMATE_ANALYSE,
    CHROMATOGRAPHE_HPLC,
    IMAGERIE_MEDICALE,
    ANALYSEUR_IMMUNOESSAI,
    REACTIFS_KITS_TEST,
    EQUIPEMENT_CULTURE_CELLULAIRE,
    EQUIPEMENT_PCR
}
